#!/bin/bash
# onboard.sh — personalize the design-to-code-qa skill for this user.
#
# Writes ~/.claude/skills/design-to-code-qa/user-prefs.md with the designer's
# workflow preferences. The SKILL.md references this file if it exists, so the
# skill phrases itself for whatever tools/conventions this user actually uses.
#
# Safe to re-run any time — overwrites user-prefs.md after confirmation.
#
# Teams that want to pre-fill answers can write their own overlay script
# that writes user-prefs.md directly and skips the prompts.

set -e

SKILL_DIR="$HOME/.claude/skills/design-to-code-qa"
PREFS="$SKILL_DIR/user-prefs.md"

mkdir -p "$SKILL_DIR"

echo "🎨 design-to-code-qa — personalize (~30 seconds)"
echo ""

if [ -f "$PREFS" ]; then
  echo "   Existing user-prefs.md found. Re-run will overwrite it."
  read -r -p "   Continue? [y/N] " REPLY
  [[ "$REPLY" =~ ^[Yy]$ ]] || { echo "   Cancelled."; exit 0; }
  echo ""
fi

# ── Q1: browser ───────────────────────────────────────────────────────────────
# Claude-in-Chrome runs on Chromium-based browsers. Detect which are installed
# on macOS and present only those. Safari / other WebKit browsers are filtered
# out since the Claude extension doesn't run there.

CHROMIUM_CANDIDATES=(
  "Google Chrome"
  "Brave Browser"
  "Microsoft Edge"
  "Arc"
  "Vivaldi"
  "Opera"
  "DuckDuckGo"
)

DETECTED=()
if [ "$(uname)" = "Darwin" ]; then
  for B in "${CHROMIUM_CANDIDATES[@]}"; do
    if [ -d "/Applications/$B.app" ]; then
      DETECTED+=("$B")
    fi
  done
fi

echo "1/3 — Browser for visual QA (Claude-in-Chrome extension is Chromium-only)"
if [ ${#DETECTED[@]} -eq 0 ]; then
  echo "    No Chromium browser detected on this machine."
  echo "    You can still use the skill; install a Chromium browser to enable the extension."
  BROWSER="none"
else
  for i in "${!DETECTED[@]}"; do
    echo "    $((i+1))) ${DETECTED[$i]}"
  done
  read -r -p "    Pick [1-${#DETECTED[@]}] (default 1): " CHOICE
  CHOICE=${CHOICE:-1}
  IDX=$((CHOICE-1))
  BROWSER="${DETECTED[$IDX]:-${DETECTED[0]}}"
fi
echo ""

# ── Q2: preview style ─────────────────────────────────────────────────────────

echo "2/3 — How do you preview components?"
echo "    1) Team / company Storybook (or similar hosted preview)"
echo "    2) Dev server in the project (npm run dev / localhost)"
echo "    3) Standalone preview.html (no build step, single file)"
echo "    4) Figma only — no separate preview"
read -r -p "    Pick [1-4] (default 2): " PREVIEW_CHOICE
PREVIEW_CHOICE=${PREVIEW_CHOICE:-2}
case "$PREVIEW_CHOICE" in
  1) PREVIEW="Team / company Storybook" ;;
  2) PREVIEW="Project dev server" ;;
  3) PREVIEW="Standalone preview.html" ;;
  4) PREVIEW="Figma only" ;;
  *) PREVIEW="Project dev server" ;;
esac
echo ""

# ── Q3: screenshot tool ───────────────────────────────────────────────────────

echo "3/3 — Which screenshot tool do you use for visual diffs?"
echo "    1) Chrome DevTools MCP (captures live browser)"
echo "    2) Claude Preview MCP (captures dev-server preview)"
echo "    3) Manual (system screenshot + paste)"
echo "    4) Other"
read -r -p "    Pick [1-4] (default 1): " SHOT_CHOICE
SHOT_CHOICE=${SHOT_CHOICE:-1}
case "$SHOT_CHOICE" in
  1) SHOT="Chrome DevTools MCP" ;;
  2) SHOT="Claude Preview MCP" ;;
  3) SHOT="Manual" ;;
  4) SHOT="Other (user-defined)" ;;
  *) SHOT="Chrome DevTools MCP" ;;
esac
echo ""

# ── Write user-prefs.md ───────────────────────────────────────────────────────

cat > "$PREFS" <<EOF
# design-to-code-qa — user preferences

<!-- Generated by onboard.sh on $(date '+%Y-%m-%d'). Re-run anytime. -->

This file is read by the design-to-code-qa skill if present. It personalizes
phrasing and tool references without changing the skill's core rules.

## Tools

- **Browser for QA:** $BROWSER
- **Preview style:** $PREVIEW
- **Screenshot tool:** $SHOT

## Notes for the skill

- When the skill says "open the preview in your browser," use **$BROWSER**.
- When it says "take a screenshot for the visual diff," use **$SHOT**.
- When it says "check the rendered component," the preview lives in: **$PREVIEW**.
EOF

echo "✅ Wrote $PREFS"
echo ""
echo "   The skill will now reference these preferences."
echo "   Edit the file directly, or re-run 'bash ~/.claude/skills/design-to-code-qa/onboard.sh' to change."
